expname: FixScmCollapse_1e-5_eps0.02 
imsize: 64
pretrain_path : # "logs/flowmatching-celeba-1028/version_1/checkpoints/model-epoch=199-val_loss=0.10195.ckpt"
trainer:
  target: pytorch_lightning.Trainer
  params:
    max_epochs: 10
    accelerator: gpu
    devices: auto
    accumulate_grad_batches: 1

model:
  target: main.LatentDiffusion
  params:
    imsize: 64
    channels: 3
    optimizer_params:
      lr: 1e-5
      weight_decay: 0.0
      beta: 0.95
      eps: 1e-8

    lr_scheduler_config: 
      target: torch.optim.lr_scheduler.StepLR
      params: 
        step_size: 1000
        gamma: 0.8 

    sample_output_dir: "./sample/celeb_config"
    sample_epoch_interval: 1
    sample_step_interval: 1000

    noise_scheduler_config:
      target: schedulers.flowmatching.FlowMatching
 
    vae_config:
      target: vae.VAELegacy

    model_config:
      target: models.dit.DiT
      params:
        imsize: ${imsize}
        patch_size: 2 
        in_channels: ${model.params.channels}
        pos_emb_type: "learned1d"
        hidden_size: 512
        qk_norm: True
        depth: 12
        num_heads: 8
        mlp_ratio: 4.0 
        learn_sigma: False  
        use_gradient_checkpointing: False 

    # model_pretrained_path: "checkpoints/flowmatching/flow_matching.ckpt"
    # model_pretrained_path: "logs/flowmatching/version_38/checkpoints/model-epoch=49-val_loss=0.11156.ckpt"
    # model_pretrained_path: "logs/flowmatching/version_38/checkpoints/model-epoch=30.ckpt"
    model_pretrained_path: "logs/flowmatching-celeba-1028/version_1/checkpoints/model-epoch=199-val_loss=0.10195.ckpt" 
    loss_type: "simple_consistency_distillation"
    r_config: 
      r_factor_max: 1.0
      r_factor_warmup_steps: 10000 
    scheduler_eps: 0.02 
      
data:
  target: data.data_wrapper.CelebDataModule
  params:
    data_dir: /pfs/haoyu/huggingface_cache/nielsr___celeb_a-faces
    batch_size: 32
    num_workers: 16
    imsize : ${imsize}