expname: flowmatching 
imsize: 64
pretrain_path :  
trainer:
  target: pytorch_lightning.Trainer
  params:
    max_epochs: 20 
    accelerator: gpu
    devices: 1 

model:
  target: main.LatentDiffusion
  params:
    batch_size: 64
    num_workers: 8
    imsize: 64
    channels: 3
    lr: 1e-4
    scheduler: Linear
    sample_output_dir: "./sample/celeb_config"
    sample_epoch_interval: 1

    noise_scheduler_config:
      target: schedulers.flowmatching.FlowMatching
      params:
        num_timesteps: 40 
 
   
    vae_config:
      target: vae.VAELegacy

    unet_config:
        target: models.unet.UNet
        params:
          channels: [64,128,128,32]
          pe_dim: 100
          with_attns: True
          norm_type: ln
          activation_type: silu
          num_res_block: 2

data:
  target: data.data_wrapper.CelebDataModule
  params:
    data_dir: nielsr/CelebA-faces
    batch_size: 64
    num_workers: 16
    imsize : 64