expname: flowmatching 
imsize: 64
pretrain_path :  
trainer:
  target: pytorch_lightning.Trainer
  params:
    max_epochs: 100 
    accelerator: gpu
    devices: 4

model:
  target: main.LatentDiffusion
  params:
    imsize: 64
    channels: 3
    lr: 1e-4
    scheduler: LinearLR
    sample_output_dir: "./sample/celeb_config"
    sample_epoch_interval: 1

    noise_scheduler_config:
      target: schedulers.flowmatching.DiscreteFlowMatching

    timestep_inverse: True
    
    vae_config:
      target: vae.VAELegacy

    model_config:
        target: models.dit.DiT
        params:
          in_channels: 3
          pos_emb_type: "learned1d"
          hidden_size: 512
          depth: 12
          num_heads: 8
          mlp_ratio: 4.0 
          learn_sigma: False  
          use_gradient_checkpointing: False 
    loss_type: "flow_matching"
    
data:
  target: data.data_wrapper.CelebDataModule
  params:
    data_dir: nielsr/CelebA-faces
    batch_size: 128
    num_workers: 32
    imsize : 64